import Head from "next/head";
import type { FC } from "react";

const NextHead: FC = () => {
  return (
    <Head>
      <title>Alien Spawn</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default NextHead;
